name: Just test

on: 
  push:
  workflow_dispatch:
    inputs:
      mavenTestProfile:
        description: |
          Maven test profile ("integration"|"subintegration"|"")
          multiple lines
        default: 'integration'

jobs:
  something_to_test:
    runs-on: ubuntu-latest

    steps:
      - name: echo action url
        run: echo "https://github.com/${{github.repository}}/actions/runs/${{ github.run_id }}"
      - name: Validate input
        if: github.event.inputs.mavenTestProfile && github.event.inputs.mavenTestProfile != 'integration' && github.event.inputs.mavenTestProfile != 'subintegration'
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('Maven test profile must be one of "integration"|"subintegration"|""')
      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1
      - name: Set SHORT_COMMIT_SHA
        run: |
          sha=${{ github.sha }}
          echo "SHORT_COMMIT_SHA=${sha:0:8}" >> $GITHUB_ENV
      - name: Print stuff
        run: |
          echo "branch name: ${{ env.BRANCH_NAME }}"
          echo "branch name: ${BRANCH_NAME}"
          echo "actor: ${{ github.actor }}"
          echo "github sha: ${{ github.sha }}"
          echo "github sha: ${GITHUB_SHA}"
          sha=${{ github.sha }}
          echo "short github sha: ${sha:0:8}"
          echo "short github sha: ${SHORT_COMMIT_SHA}"
          echo "github sha: ${GITHUB_SHA:0:8}"

