name: Just test

on: 
  push:
  workflow_dispatch:
    inputs:
      prebuild:
        description: Pre-build skipping tests (true|false)
        default: 'false'
      mavenFlags:
        description: Maven flags
        default: -P integration
      openposeContainerPort:
        description: OpenPose container port
        required: true
        default: 5002
      storyId:
        description: Story ID (e.g. 1234)
        required: true

jobs:
  something_to_test:
    runs-on: ubuntu-latest
    env:
      COMMIT_PREFIX: ''
      PR_BODY_STORY_TEXT: ''

    steps:
      - name: Log inputs
        run: |
          echo "::set-output name=matrix::"
            Pre-build skipping tests: ${{ contains(github.event.inputs.prebuild, 'true') }}
            Maven flags: ${{ github.event.inputs.mavenFlags }}
            OpenPose container port: ${{ github.event.inputs.openposeContainerPort }}
            Story ID: ${{ github.event.inputs.storyId }}
          "

      # compute inputs
      - name: Set AIST_OPENPOSE_API_ORIGIN
        if: github.event.inputs.storyId
        run: echo "AIST_OPENPOSE_API_ORIGIN=http://aist-openpose-api:${{ github.event.inputs.openposeContainerPort }}" >> $GITHUB_ENV
      - name: Set COMMIT_PREFIX
        if: github.event.inputs.storyId
        run: echo "COMMIT_PREFIX=[${{ github.event.inputs.storyId }}] " >> $GITHUB_ENV
      - name: Set PR body text
        if: github.event.inputs.storyId
        run: echo "PR_BODY_STORY_TEXT=Associated with [${{ github.event.inputs.storyId }}]" >> $GITHUB_ENV
      - name: Verify Maven flags
        continue-on-error: true
        if: github.event.inputs.mavenFlags
        run: echo ${{ github.event.inputs.mavenFlags }}
      - name: Set SHORT_COMMIT_SHA
        run: |
          sha=${{ github.sha }}
          echo "SHORT_COMMIT_SHA=${sha:0:8}" >> $GITHUB_ENV

      - name: echo action url
        run: echo "https://github.com/${{github.repository}}/actions/runs/${{ github.run_id }}"
      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1
      - name: Set BRANCH_NAME
        uses: nelonoel/branch-name@v1.0.1

