name: Just test

on: 
  push:
    paths:
      - 'some_dir/**/*.*'
  workflow_dispatch:
    inputs:
      prebuild:
        description: Pre-build skipping tests (true|false)
        default: 'false'
      mavenFlags:
        description: Maven flags
        default: -P integration
      openposeContainerPort:
        description: OpenPose container port
        required: true
        default: 5002
      storyId:
        description: Story ID (e.g. 1234)
        required: true

jobs:

  find_free_port:
    runs-on: ubuntu-latest

    outputs:
      port: ${{ steps.findFreePort.outputs.port }}

    env:
      LOWER_BOUND: 5000
      UPPER_BOUND: 6000

    steps:
      - name: netstat
        run: netstat -aln
      - name: Find free port
        id: findFreePort
        run: |
          open_port=$(netstat -aln | awk '
            $6 == "LISTEN" {
              if ($4 ~ "[.:][0-9]+$") {
                split($4, a, /[:.]/);
                port = a[length(a)];
                p[port] = 1
              }
            }
            END {
              for (i = 3000; i < 65000 && p[i]; i++){};
              if (i == 65000) {exit 1};
              print i
            }
          ')
          echo "found free port ${open_port}"
          echo "::set-output name=port::${open_port}"
  something_to_test:
    runs-on: ubuntu-latest

    needs: find_free_port

    env:
      FREE_PORT: ${{ needs.find_free_port.outputs.port }}
      PR_BODY_STORY_TEXT: ''
      PR_COMMIT_MESSAGE: |
        [ch${{ github.event.inputs.storyId }}] Update snapshots (automated commit)
        Generated by [${{ github.action }} run nr. ${{ github.run_number }}](https://github.com/${{github.repository}}/actions/runs/${{ github.run_id }})

        ${{ github.event.inputs.comment }}

        Pre-build skipping tests: ${{ contains(github.event.inputs.prebuild, 'true') }}
        Maven flags: ${{ github.event.inputs.mavenFlags }}
      PR_TITLE: '[Bot] Update snapshots by ${{ github.action }} run nr. ${{ github.run_number }}'
      PR_BODY: |
        Generated by [${{ github.action }} run nr. ${{ github.run_number }}](https://github.com/${{github.repository}}/actions/runs/${{ github.run_id }})

        Associated with [ch${{ github.event.inputs.storyId }}]

        ${{ github.event.inputs.comment }}

        Pre-build skipping tests: ${{ contains(github.event.inputs.prebuild, 'true') }}
        Maven flags: ${{ github.event.inputs.mavenFlags }}
      PR_COMMITTER: '${{ github.actor }} <admin+devOps@amb-technology.ai>'
     

    steps:
      - name: Log inputs
        run: |
          echo "
            Pre-build skipping tests: ${{ contains(github.event.inputs.prebuild, 'true') }}
            Maven flags: ${{ github.event.inputs.mavenFlags }}
            OpenPose container port: ${{ github.event.inputs.openposeContainerPort }}
            Story ID: ${{ github.event.inputs.storyId }}
          "
      - name: Set BRANCH_NAME
        uses: nelonoel/branch-name@v1.0.1
      - name: Set PR_BRANCH
        run: echo "PR_BRANCH=${{ env.BRANCH_NAME }}_update-snapshots_${{ github.run_number }}" >> $GITHUB_ENV

      # compute inputs
      - name: Set AIST_OPENPOSE_API_ORIGIN
        if: github.event.inputs.storyId
        run: echo "AIST_OPENPOSE_API_ORIGIN=http://aist-openpose-api:${{ github.event.inputs.openposeContainerPort }}" >> $GITHUB_ENV
      - name: Set COMMIT_PREFIX
        if: github.event.inputs.storyId
        run: echo "COMMIT_PREFIX=[${{ github.event.inputs.storyId }}] " >> $GITHUB_ENV
      - name: Set PR body text
        if: github.event.inputs.storyId
        run: echo "PR_BODY_STORY_TEXT=Associated with [${{ github.event.inputs.storyId }}]" >> $GITHUB_ENV
      - name: Verify Maven flags
        continue-on-error: true
        if: github.event.inputs.mavenFlags
        run: echo ${{ github.event.inputs.mavenFlags }}
      - name: Set SHORT_COMMIT_SHA
        run: |
          sha=${{ github.sha }}
          echo "SHORT_COMMIT_SHA=${sha:0:8}" >> $GITHUB_ENV

      - name: echo action url
        run: echo "https://github.com/${{github.repository}}/actions/runs/${{ github.run_id }}"
      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1
      - name: Set BRANCH_NAME
        uses: nelonoel/branch-name@v1.0.1

