name: Just test

# TODO: change to [workflow_dispatch]
on: push

jobs:
  run_integration_steps:
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1
      - name: Set SHORT_COMMIT_SHA
        run: |
          sha=${{ github.sha }}
          echo "SHORT_COMMIT_SHA=${sha:0:8}" >> $GITHUB_ENV
      - name: Print stuff
        run: |
          echo "branch name: ${{ env.BRANCH_NAME }}"
          echo "branch name: ${BRANCH_NAME}"
          echo "actor: ${{ github.actor }}"
          echo "github sha: ${{ github.sha }}"
          echo "github sha: ${GITHUB_SHA}"
          sha=${{ github.sha }}
          echo "short github sha: ${sha:0:8}"
          echo "short github sha: ${SHORT_COMMIT_SHA}"

